# Generated by Django 4.2.5 on 2023-09-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_latitude_notes_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='longitude',
        ),
    ]
