# Generated by Django 4.2.5 on 2023-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_notes_latitude_remove_notes_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=6),
        ),
    ]
