# Generated by Django 4.2.5 on 2023-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='priority',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], default='Low', max_length=6),
        ),
    ]
